### ISSUE TITLE
Unable to get pvxs.dll work

### ISSUE THREAD

**Issue by psharma-stfc** [epics-base/pvxs#80]
**Help Requested**

I have created a sample C++ project that references `pvxs.dll` and other DLLs (`ca.dll`, `Com.dll`, `dbCore.dll`, `dbRecStd.dll`, `event.dll`, `event_core.dll`, `event_extra.dll`). The project includes a `main.cpp` file containing code taken from `example/simpleget.cpp`.

However, the code fails with the following errors:

**main.cpp output:**
```cpp
Value reply = ctxt.get(pv_name).exec()->wait(5.0);
// Fetch PV TEST:Model_RBV and wait up to 5 seconds for a reply.
// (Throws an exception on error, including timeout)
Exception: bad allocation  <<--- for string PV

Exception: Operation has custom .result() callback <<-- for numeric PV
```

I believe `pvxs.dll` is built properly (I followed the steps mentioned in the documentation section "Building from Source") since the configuration code works:
```cpp
// This is working fine
std::cout << "Configure client using $EPICS_PVA_*";
auto ctxt(client::Context::fromEnv());

std::cout << "Effective config\n" << ctxt.config();
```

Do you think there might be an dependency issue with the `pvxs.dll`? Any suggestions are much appreciated.

One more thing: I noticed that you have Actions defined for this repo (I'm interested in `VS 2019 DLL` and `Cross mingw64 DLL`), but the Artifacts are all expired. Would you be able to provide them?

Thank you in advance.

**Comment by mdavidsaver** [comment]
> I have created a sample C++ project ...

Could you provide some detail?  Do you mean a MSVC project?

fyi. mixing a EPICS Makefile build with a MSVC project build should be possible, but requires detailed knowledge of, and careful attention to, compiler and linker flags.


> ```c++
> Exception: bad allocation  <<--- for string PV
> ```

Unless you have some fantastically long PV name, this sort of error suggests to me an ABI mis-match between your two build environments.

> Do you think there might be an dependency issue with the `pvxs.dll`?

No.  Getting far enough to see a bad_alloc from PVXS means the DLL was loaded successfully.

> I noticed that you have Actions defined for this repo ...

Which you can run yourself by creating a personal fork of this repository.

**Comment by psharma-stfc** [comment]
Hi, you're right, the issue was with the different in the build environment. Thank you for the quick response, really appreciate it.
