### ISSUE TITLE
Search retry step of the client channel is never reset

### ISSUE THREAD

**Issue by anzez** [epics-base/pvxs#84]
**Describe the bug**
If a monitored PV which was offline for a longer period of time goes down again, PVXS monitor will wait up to (worst case of) 30 seconds before trying to reconnect.

This is because the search retry step (`Channel::nSearch`) keeps increasing up to 30 (seconds) while the PV is offline, however once it reconnects, the step doesn't get reset. On the next disconnection it immediately starts at 30. So unless it also triggers the hurryUp, it ends up having worst case of 30 second reconnection delay.

**To Reproduce**
1. Run a pvxmonitor on given pv and wait for 10 minutes - during this time the search retry step (`Channel::nSearch`) will reach 30
2. Start pvxs server - thanks to `hurryUp` it will connect in <6 seconds but the search retry step will remain 30
3. Kill the pvxs server and start it again - due to `pokeHoldoff=30s` it won't trigger the `hurryUp`, instead it will take up to (worst case) 30 seconds to reconnect

**Expected behavior**
`pvxmonitor` reconnection in step 3 should happen in a matter of seconds (as it is the case with `pvget -m`).

**Information (please complete the following):**
 - PVXS Version or Git commit ID: 1.3.1+
 - EPICS Base Version: 7.0.8
 - libevent Version:
 - EPICS_HOST_ARCH: linux-x86_64
 - Host OS: RHEL 8.5

**Additional context**
Because reconnected channels are only removed from buckets on the next iteration, with the short-lived PV connection from step 2 we end up having two instances of the same channel in two different buckets. This may increase the odds of faster reaching the reconnection in step 3, but the worst case is still ~30 seconds.

**Diagnosis**
The problem is that search retry step of the client channel (`Channel::nSearch`) is never reset. I suggest the following fix to have it reset to 0 once the channel is reconnected:
```
Index: pvxs/src/client.cpp
===================================================================
--- pvxs/src/client.cpp	(revision 158544)
+++ pvxs/src/client.cpp	(working copy)
@@ -904,6 +904,7 @@
             chan->conn = Connection::build(self.shared_from_this(), serv);
 
             chan->conn->pending[chan->cid] = chan;
+            chan->nSearch = 0u;
             chan->state = Channel::Connecting;
 
             chan->conn->createChannels();
```

**Comment by mdavidsaver** [comment]
> I suggest the following fix to have it reset to 0 once the channel is reconnected:

@anzez  I agree with your assessment.  Would you like to create a pull request?

**Comment by anzez** [comment]
@mdavidsaver Sure, can you give me access to push to the repository?
